#! /bin/bash

includepath="-I../include/ -I../include/encode/ -I../include/mysql/"
libpath="-L../lib/ -lmysqlclient -lencode"
g++ chat_server.cpp ../include/db.cpp -o chat_server $includepath $libpath
echo "compiled chat_server"