#! /bin/bash

includepath="-I../include/ -I../include/encode/ -I../include/mysql/"
libpath="-L../lib/ -lmysqlclient -lencode"
g++ testdb.cpp ../include/db.cpp -o testdb $includepath $libpath
echo "compiled testdb"