.pragma library
//define const
const SOCKET_LOG_UP = 0
const SOCKET_LOG_IN = 1
const SOCKET_ADD_CONTACT = 2
const SOCKET_ANSWER_ADD = 3
//CLIENT signale
const CLIENT_FALSE = 0
const CLIENT_TRUE = 1
const CLIENT_ACCOUNT_REGISTED = 2
const CLIENT_ACCOUNT_NOT_REGISTED = 3
const CLIENT_WRONG_PASSWORD = 4
const CLIENT_ACCOUNT_ONLINE = 5
const CLIENT_BUFFER_ADD_CONTACT = 6
const CLIENT_BUFFER_SEND_MESSAGE = 7
const CLIENT_ADD_CONTACT_REQUEST = 8
const CLIENT_AGREE_ADD_CONTACT = 9
const CLIENT_REJECT_ADD_CONTACT = 10
const CLIENT_ANSWER_YES = 11
const CLIENT_ANSWER_NO = 12
//global variable
var account
var contact
